In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel('students.xlsx')
print(df)

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45


In [4]:
marks=df['Marks'].to_numpy()
print('Numpy Array of Marks')
print(marks)

Numpy Array of Marks
[85 90 78 92 90 45]


In [5]:
print('Highest Mark',np.max(marks))

Highest Mark 92


In [6]:
print('Lowest Mark',np.min(marks))

Lowest Mark 45


In [9]:
print('Average Mark',np.mean(marks))

Average Mark 80.0


# .loc:label based
# .iloc: index based

In [34]:
print('Original Dataframe') # pandas method
print(df)
print('Location: Label Based')
print(df.loc[2,['Name','Marks']])  

Original Dataframe
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45
Location: Label Based
Name     Bob
Marks     78
Name: 2, dtype: object


In [35]:
print('Original Dataframe')  # pandas method
print(df)
print('Location: Index Based')
print(df.iloc[2,[1,2]]) 

Original Dataframe
    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45
Location: Index Based
Age      21
Marks    78
Name: 2, dtype: object


# Axis in Numpy: 
    1. Axis 0: vertical direction: works columns-wise
    2. Axis 1: horizontal direction: works rows-wise


# We have two students marks in 3 subjects
    # [[45,50,49],[30,45,49]]

In [41]:
marks_arr=np.array([[5,2,9],[10,40,60]])
print(marks_arr)

[[ 5  2  9]
 [10 40 60]]


In [42]:
print('Sum down in each column',np.sum(marks_arr,axis=0))

Sum down in each column [15 42 69]


In [44]:
print('Sum down in each row',np.sum(marks_arr,axis=1))

Sum down in each row [ 16 110]


In [45]:
print('Numpy Array of marks')
print(marks)

Numpy Array of marks
[85 90 78 92 90 45]


In [46]:
print(df)

    Name  Age  Marks
0   John   20     85
1  Alice   22     90
2    Bob   21     78
3   Sara   23     92
4    Sam   25     90
5  Rohit   23     45


# Find the student name who got highest marks

In [50]:
topper=df.loc[df['Marks'].idxmax(),'Name']
print('Top Student Name',topper)

Top Student Name Sara


In [51]:
last=df.loc[df['Marks'].idxmin(),'Name']
print('Last Student Name',last)

Last Student Name Rohit


In [54]:
first_in_class = df.loc[df['Marks'].idxmax(), 'Name']
print('First in Class Student Name:', first_in_class)

First in Class Student Name: Sara


In [55]:
print('Next Example')

Next Example


In [66]:
top_index=df['Marks'].idxmax()
print(top_index)  # kira dari 0,1,2,3 dapat la sara
top_students=df.iloc[top_index,df.columns.get_loc('Name')]
print('Top of the class is:',top_students)

3
Top of the class is: Sara
