# Numpy (Numerical Python) Introduction and usage:
## Numpy is a python library. Use for fast numerical computation.
### We will use numpy in this Jupyter Notebook.

# One Dimensional Array (1-D)

In [1]:
import numpy as np

In [2]:
array1=np.array([10,20,30,40,50])

In [3]:
print(array1)

[10 20 30 40 50]


## Two Dimensional Array (2-D)

In [5]:
array_two=np.array([[10,20,30],[40,50,70]])

In [7]:
print(array_two)

[[10 20 30]
 [40 50 70]]


# Three Dimensional Array (3-D Array)

In [8]:
array_three=np.array([[[10,20,30],[40,50,70]],[[10,20,30],[40,50,70]]])

In [9]:
print(array_three)

[[[10 20 30]
  [40 50 70]]

 [[10 20 30]
  [40 50 70]]]


# Existing dimensional array
## Find out dimensional on NumPy array

In [11]:
print("First Array Dimensional: \t", array1.ndim)

First Array Dimensional: 	 1


In [12]:
print("Second Array Dimensional: \t", array_two.ndim)

Second Array Dimensional: 	 2


In [13]:
print("Third Array Dimensional: \t", array_three.ndim)

Third Array Dimensional: 	 3


# Write an array of 5 students marks using NumPy (1D Array)
    ## Marks are: 80,70,70,99,89

In [18]:
marks_1d=np.array([80,70,70,99,89])

In [19]:
print("1D Array (Marks of 5 Students):")

1D Array (Marks of 5 Students):


In [22]:
print(marks_1d)

[80 70 70 99 89]


In [23]:
marks_1d=np.array([80,70,70,99,89])
print("1D Array (Marks of 5 Students):")
print(marks_1d)

1D Array (Marks of 5 Students):
[80 70 70 99 89]


# Write an array to take Marks 5 students in 3 subjects using NumPy (2D Array)
## Math, English, Chemistry
### [[50,45,49],[40,42,45],[35,40,46],[39,40,45],[48,40,40]]

In [24]:
array_marks_subject=np.array([[50,45,49],[40,42,45],[35,40,46],[39,40,45],[48,40,40]])

In [25]:
print("2D Array Example")

2D Array Example


In [26]:
print(array_marks_subject)

[[50 45 49]
 [40 42 45]
 [35 40 46]
 [39 40 45]
 [48 40 40]]


In [27]:
array_marks_subject=np.array([[50,45,49],[40,42,45],[35,40,46],[39,40,45],[48,40,40]])
print("2D Array Example")
print(array_marks_subject)

2D Array Example
[[50 45 49]
 [40 42 45]
 [35 40 46]
 [39 40 45]
 [48 40 40]]


# Write an array to take Marks 4 students in 3 subjects for 2 semester using NumPy (3D Array)
    ## Students Name are: 'Amit','Sha','Xi','Arif'
    ## Math, English, Chemistry
    ## Two Semester : Sem1, Sem2
    ## 4*3*2 (4 into 3 into 2)
    ## [[[85,88],[78,82],[90,95]], [[76,70],[40,45],[90,90]], [[80,86],[67,87],[97,67]], [[82,78],[56,76],[99,65]]]


## Camni boleh susunan dia:
## [[[85,88],[78,82],[90,95]], [[76,70],[40,45],[90,90]], [[80,86],[67,87],[97,67]], [[82,78],[56,76],[99,65]]]


## Camni pon boleh susunan dia (ni untuk kemas je):
## marks_subject_sem=np.array([
    [[85,88],[78,82],[90,95]],
    [[76,70],[40,45],[90,90]],
    [[80,86],[67,87],[97,67]],
    [[82,78],[56,76],[99,65]]
])

In [34]:
marks_subject_sem=np.array([
    [[85,88],[78,82],[90,95]],
    [[76,70],[40,45],[90,90]],
    [[80,86],[67,87],[97,67]],
    [[82,78],[56,76],[99,65]]
])

In [35]:
print('Marks 4 students in 3 subjects for 2 semester')

Marks 4 students in 3 subjects for 2 semester


In [36]:
print(marks_subject_sem)

[[[85 88]
  [78 82]
  [90 95]]

 [[76 70]
  [40 45]
  [90 90]]

 [[80 86]
  [67 87]
  [97 67]]

 [[82 78]
  [56 76]
  [99 65]]]


In [37]:
marks_subject_sem=np.arraymarks_subject_sem=np.array([
    [[85,88],[78,82],[90,95]],
    [[76,70],[40,45],[90,90]],
    [[80,86],[67,87],[97,67]],
    [[82,78],[56,76],[99,65]]
])
print('Marks 4 students in 3 subjects for 2 semester')
print(marks_subject_sem)

Marks 4 students in 3 subjects for 2 semester
[[[85 88]
  [78 82]
  [90 95]]

 [[76 70]
  [40 45]
  [90 90]]

 [[80 86]
  [67 87]
  [97 67]]

 [[82 78]
  [56 76]
  [99 65]]]


# Write an array to take weather 2 cities in 3 days for three times in a day: Morning, noon, evening. - using NumPy (3D Array)
    ## Cities Name are: Kuala Lumpur, Delhi
    ## Saturday, Sunday, Monday
    ## Three time slot : Morning, noon, evening
    ## Tempature: KL-[[28, 32, 29],[27, 31, 28],[26, 30, 27]]
    ## Tempature: Delhi- [[20, 30, 25],[22, 33, 27],[21, 31, 26]]
    ## 3D Array akan jadi [[[28, 32, 29],[27, 31, 28],[26, 30, 27]],[[20, 30, 25],[22, 33, 27],[21, 31, 26]]]
## Create one 3D Array using Numpy and print it.

In [57]:
weather_array=[[[28, 32, 29],[27, 31, 28],[26, 30, 27]],[[20, 30, 25],[22, 33, 27],[21, 31, 26]]]

In [56]:
print(weather_array)

[[[28, 32, 29], [27, 31, 28], [26, 30, 27]], [[20, 30, 25], [22, 33, 27], [21, 31, 26]]]


# Yang bawah ni exercise lain i just buat sendiri (Weather Data using NumPy (3D Array)

In [53]:
weather=np.array([[
        [28, 32, 29],   # KL Saturday (Morning, Noon, Evening)
        [27, 31, 28],   # Sunday
        [26, 30, 27]],    # Monday

        [[20, 30, 25],  # Delhi Saturday (Morning, Noon, Evening)
        [22, 33, 27],   # Sunday
        [21, 31, 26]]]) # Monday

In [49]:
print('Weather Data (°C): ')

Weather Data (°C): 


In [50]:
print(weather)

[[[28 32 29]
  [27 31 28]
  [26 30 27]]

 [[20 30 25]
  [22 33 27]
  [21 31 26]]]


In [52]:
weather=np.array([[
        [28, 32, 29],   # KL Saturday (Morning, Noon, Evening)
        [27, 31, 28],   # Sunday
        [26, 30, 27]],  # Monday

        [[20, 30, 25],  # Delhi Saturday (Morning, Noon, Evening)
        [22, 33, 27],   # Sunday
        [21, 31, 26]]]) # Monday
print('Weather Data (°C): ')
print(weather)

Weather Data (°C): 
[[[28 32 29]
  [27 31 28]
  [26 30 27]]

 [[20 30 25]
  [22 33 27]
  [21 31 26]]]


# Basic Information
    ## Shape: rows and columns
    ## Size: number of elements
    ## Dimension: return dimension 1, 2, 3 ....
    ## Data Type: return stored data values type

In [58]:
print(array1)

[10 20 30 40 50]


In [63]:
print("Shape of array1: ",array1.shape)

Shape of array1:  (5,)


In [65]:
print("Size of array1: ",array1.size)

Size of array1:  5


In [66]:
print('Dimension: ',array1.ndim)

Dimension:  1


In [78]:
print('Data Type: ',array1.dtype)  # Output int64 Integer using 64 bits (8 bytes), kalau float(ada decimal) tnye chatgpt

Data Type:  int64


In [68]:
students=np.array(['ali','shi','xi','meena','ziva'])

In [70]:
print(students)

['ali' 'shi' 'xi' 'meena' 'ziva']


In [71]:
print('Shape of Array: ',students.shape)

Shape of Array:  (5,)


In [72]:
print("Number of Students: ",students.size)

Number of Students:  5


In [76]:
print('Data Type: ',students.dtype)  #output <U5 - maksud huruf(character) paling banyak dalam data tu adalah 5 

Data Type:  <U5


# Mathematical Operation

In [79]:
print(array1)

[10 20 30 40 50]


In [82]:
total=np.sum(array1)

In [83]:
print(total)

150


In [84]:
print(array1)
total=np.sum(array1)
print(total)

[10 20 30 40 50]
150


In [85]:
print('Mean: ',np.mean(array1))

Mean:  30.0


In [87]:
print('Min: ',np.min(array1))

Min:  10


In [88]:
print('Max: ',np.max(array1))

Max:  50


In [89]:
print('Index of Min: ',np.argmin(array1))

Index of Min:  0


In [90]:
print('Index of Max: ',np.argmax(array1))

Index of Max:  4


In [91]:
our_arr=np.array([100,200,300,7000,400,500,300,1900,600])

In [92]:
print(our_arr)

[ 100  200  300 7000  400  500  300 1900  600]


# Searching and Sorting Example in 1D Array

In [95]:
sorted_arr=np.sort(our_arr)
print('***Sorted Array***')
print(sorted_arr)

***Sorted Array***
[ 100  200  300  300  400  500  600 1900 7000]


In [97]:
print('Is there any item greater than 500?: ',np.any(sorted_arr>500))

Any item greater than 500?:  True


In [100]:
print('All greater than 99?: ',np.all(sorted_arr>99))

All greater than 99?:  True


In [101]:
print('Where values >500',np.where(sorted_arr>500))

Where values >500 (array([6, 7, 8]),)


In [102]:
print('All Number greater than 500')
for num in np.where(sorted_arr>500):
    print (num)

All Number greater than 500
[6 7 8]


In [117]:
print('All Number greater than 500')
for num in sorted_arr>500:
    print (num)

All Number greater than 500
False
False
False
False
False
False
True
True
True


In [120]:
selected_values=sorted_arr[sorted_arr>500]

In [121]:
print(selected_values)

[ 600 1900 7000]


In [130]:
for num in selected_values:
    print(num)

    #or cara ni boleh juga 

for num in sorted_arr[sorted_arr>500]:
    print(num)

600
1900
7000
600
1900
7000


In [103]:
print(sorted_arr)

[ 100  200  300  300  400  500  600 1900 7000]


In [106]:
print(np.min(sorted_arr))

100


In [110]:
print('Index of Min: ',np.argmin(sorted_arr))

Index of Min:  0


In [111]:
print('Index of Max: ',np.argmax(sorted_arr))

Index of Max:  8


In [114]:
print('Min: ',np.min(sorted_arr))

Min:  100


In [115]:
print('Max: ',np.max(sorted_arr))

Max:  7000


# Slicing 1D Array
    1. To take elements from starting index to end index
    2. Example - [start:end]

In [138]:
print(sorted_arr)

[ 100  200  300  300  400  500  600 1900 7000]


In [137]:
slice_our_arr=sorted_arr[1:3]
print(slice_our_arr)

[200 300]


# Starting from an index and going till last

In [141]:
print(sorted_arr[3:])  #[3:] means → start from index 3 (the 4th element) and take everything until the end

[ 300  400  500  600 1900 7000]


In [142]:
print(sorted_arr[:4])  # [:4] means → start from the beginning (index 0) and stop before index 4

[100 200 300 300]


In [140]:
print(sorted_arr[:5])

[100 200 300 300 400]


# Step
    ## [start:end:step]
    ## Step: every step element

In [144]:
print(sorted_arr)

[ 100  200  300  300  400  500  600 1900 7000]


In [143]:
our_slice=sorted_arr[1:6]
print(our_slice)

[200 300 300 400 500]


In [147]:
every_third_element=sorted_arr[::3]  #[start : stop : step] - start → empty, so it starts from the beginning, stop → empty, so it goes until the end, step = 3 → take every 3rd element
print(every_third_element)

[100 300 600]


In [146]:
print('Original Array')
print(sorted_arr)
print('Every Third Element')
every_third_element=sorted_arr[::3]
print(every_third_element)

Original Array
[ 100  200  300  300  400  500  600 1900 7000]
Every Third Element
[100 300 600]


# Slice Reverse

In [149]:
print('Original Array')
print(sorted_arr)
print('Revers Array: ')
print(sorted_arr[::-1])

Original Array
[ 100  200  300  300  400  500  600 1900 7000]
Revers Array: 
[7000 1900  600  500  400  300  300  200  100]


In [151]:
print('Last five elements')
print(sorted_arr[-5:])

Last five elements
[ 400  500  600 1900 7000]


In [153]:
print('Slicing Done')

Slicing Done
