In [1]:
# We are going to start TensionFlow Basics here

In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.19.0


In [8]:
# Create Tnesor with constant
# function that we can use to create
scalar=tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [9]:
scalar.ndim

0

In [11]:
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [12]:
vector.ndim

1

In [14]:
matrix=tf.constant([[5,9],[9,11]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  9],
       [ 9, 11]], dtype=int32)>

In [15]:
matrix.ndim

2

In [23]:
second_matrix=tf.constant([[5,7],[3,8],
                           [3,9],
                           [4,2],
                           [8,6]])


In [19]:
second_matrix

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[5, 7],
       [3, 8],
       [3, 9],
       [4, 2],
       [8, 6]], dtype=int32)>

In [21]:
second_matrix.ndim

2

In [27]:
third_matrix = tf.constant([
    [[1,  2,  3],
    [2,  4,  5]],
    [[7,  9,  3],
    [10, 4,  5]],
    [[11, 2,  3],
    [2,  4, 15]],
])

third_matrix


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  4,  5]],

       [[ 7,  9,  3],
        [10,  4,  5]],

       [[11,  2,  3],
        [ 2,  4, 15]]], dtype=int32)>

In [28]:
third_matrix.ndim

3

In [29]:
second_matrix=tf.constant([[5.5,7.3],[3.45,8.25],
                           [3.11,9.23],
                           [4.34,2.34],
                           [8.4,6.23]],dtype=tf.float16)
print(second_matrix)

tf.Tensor(
[[5.5  7.3 ]
 [3.45 8.25]
 [3.11 9.23]
 [4.34 2.34]
 [8.4  6.23]], shape=(5, 2), dtype=float16)


In [30]:
# singel number that means scalar
scalar=tf.constant(5)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [31]:
# a number with direction
vector=tf.constant([10,10,20,30])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 10, 20, 30], dtype=int32)>

In [33]:
# a 2-D array of numbers
matrix=tf.constant([[10,20],[30,40]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [34]:
# Tensor: an n-dimensional array of numbers (n=0,n=1,n=2....)
tensor=tf.constant([[[1,2],[3,4],[5,6],[7,8]]])
tensor

<tf.Tensor: shape=(1, 4, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]], dtype=int32)>

In [38]:
# Find the shape, rank and size of the tensors
print('Scalar Information')
print('Shape:',scalar.shape)
print('Dimension:',scalar.ndim)
print('Rank:',tf.rank(scalar))
print('Size',tf.size(scaler).numpy())

Scalar Information
Shape: ()
Dimension: 0
Rank: tf.Tensor(0, shape=(), dtype=int32)
Size 1


In [43]:
print('Vector Information')
print('Shape:', vector.shape)
print('Dimension:', vector.ndim)
print('Rank:',tf.rank(vector).numpy())
print('Size:',tf.size(vector))

Vector Information
Shape: (4,)
Dimension: 1
Rank: 1
Size: tf.Tensor(4, shape=(), dtype=int32)


In [44]:
# Creating Tensor using Variable
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [45]:
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [46]:
changeable_tensor[1].assign(15)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 15], dtype=int32)>

In [48]:
changeable_tensor[1].assign(75)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 75], dtype=int32)>

In [49]:
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [51]:
#unchangeable_tensor[0].assign(12)
#unchangeable_tensor
#this will be an error because you can't change constant tensor. They are Immutable i.e. unchangeable

In [54]:
# Random Tensors
random_tensor=tf.random.Generator.from_seed(42)
random_tensor=random_tensor.normal(shape=(3,2))
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [55]:
random_tensor_2=tf.random.uniform(shape=(300,150),minval=0,maxval=1)
random_tensor_2

<tf.Tensor: shape=(300, 150), dtype=float32, numpy=
array([[0.6030729 , 0.51873136, 0.05049849, ..., 0.54035366, 0.5212617 ,
        0.11411929],
       [0.8891636 , 0.14413297, 0.23472643, ..., 0.1196233 , 0.9283534 ,
        0.2445327 ],
       [0.790722  , 0.03056192, 0.10673976, ..., 0.42485178, 0.8689096 ,
        0.7838634 ],
       ...,
       [0.24166775, 0.8725382 , 0.06350577, ..., 0.21121824, 0.65343773,
        0.24562466],
       [0.772251  , 0.29237616, 0.79346097, ..., 0.97420335, 0.60125303,
        0.5598972 ],
       [0.8120657 , 0.80543673, 0.7643217 , ..., 0.4112774 , 0.02642393,
        0.676986  ]], dtype=float32)>

In [57]:
#same seed same tensors
random_tensor_3=tf.random.Generator.from_seed(42)
random_tensor_3=random_tensor_3.normal(shape=(3,2))
random_tensor_4=tf.random.Generator.from_seed(42)
random_tensor_4=random_tensor_4.normal(shape=(3,2))
random_tensor_3,random_tensor_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [58]:
#difference seed different tensors
random_tensor_3=tf.random.Generator.from_seed(42)
random_tensor_3=random_tensor_3.normal(shape=(3,2))
random_tensor_4=tf.random.Generator.from_seed(42)
random_tensor_4=random_tensor_4.normal(shape=(3,2))
random_tensor_3,random_tensor_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [67]:
#creating tensors using zeros
tensor_zeros = tf.zeros(shape=(3, 4), dtype=tf.int16)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [68]:
tensor_zeros = tf.zeros(shape=(3, 4), dtype=tf.float32)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [69]:
tensor_ones = tf.ones(shape=(3, 4), dtype=tf.int16)
tensor_ones

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)>

In [70]:
import numpy as np
numpy_array=np.arange(1,25,dtype=np.int16)
numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [71]:
tensor_numpy=tf.constant(numpy_array,shape=(2,3,4))
tensor_numpy

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

In [74]:
print('Vector Information')
print('Shape:', tensor_numpy.shape)
print('Dimension:', tensor_numpy.ndim)
print('Rank:',tf.rank(tensor_numpy).numpy())
print('Size:',tf.size(tensor_numpy))
print('DataType of elements:',tensor_numpy.dtype)
print('Element along axis 0:',tensor_numpy.shape[0])
print('Element along axis 1:',tensor_numpy.shape[1])
print('Element along axis 2:',tensor_numpy.shape[2])
print('Total number of element: \t',tf.size(tensor_numpy).numpy())
#

Vector Information
Shape: (2, 3, 4)
Dimension: 3
Rank: 3
Size: tf.Tensor(24, shape=(), dtype=int32)
DataType of elements: <dtype: 'int16'>
Element along axis 0: 2
Element along axis 1: 3
Element along axis 2: 4
Total number of element: 	 24


In [80]:
# working with items each dimension
# first three elements
tensor_numpy[:3,:3,:3]

<tf.Tensor: shape=(2, 3, 3), dtype=int16, numpy=
array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[13, 14, 15],
        [17, 18, 19],
        [21, 22, 23]]], dtype=int16)>

In [81]:
# first two elements of each dimension
tensor_numpy[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int16, numpy=
array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]], dtype=int16)>

**Arithmetic Operation with Tensors**


*  Add
*  Sub
*  Multi
*  Div

In [85]:
tensor_one=tf.constant([[11,9],[12,5]])
tensor_one

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  9],
       [12,  5]], dtype=int32)>

In [91]:
#tensor_one+15
tf.add(tensor_one,15)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 24],
       [27, 20]], dtype=int32)>

In [92]:
#tensor_one-5
tf.subtract(tensor_one,5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 4],
       [7, 0]], dtype=int32)>

In [93]:
#tensor_one*2
tf.multiply(tensor_one,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 18],
       [24, 10]], dtype=int32)>

In [94]:
#tensor_one/2
tf.divide(tensor_one,2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5.5, 4.5],
       [6. , 2.5]])>

In [97]:
tf.square(tensor_one)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  81],
       [144,  25]], dtype=int32)>

In [100]:
second_matrix=tf.constant([[8,16],[64,8.25],
                           [625,9.23],
                           [125,2.34],
                           [169,6.23]],dtype=tf.float16)
print(second_matrix)

tf.Tensor(
[[  8.    16.  ]
 [ 64.     8.25]
 [625.     9.23]
 [125.     2.34]
 [169.     6.23]], shape=(5, 2), dtype=float16)


In [101]:
tf.sqrt(second_matrix)

<tf.Tensor: shape=(5, 2), dtype=float16, numpy=
array([[ 2.828,  4.   ],
       [ 8.   ,  2.873],
       [25.   ,  3.037],
       [11.18 ,  1.529],
       [13.   ,  2.496]], dtype=float16)>

**Exercise**

Create two tensors with random values between 0 and 1, shape is [6,300]
Find out the follow details:

* Number of elements
* Rank,
* Shape

In [102]:
tensor_a = tf.random.uniform(shape=[6, 300], minval=0, maxval=1)
tensor_b = tf.random.uniform(shape=[6, 300], minval=0, maxval=1)

In [104]:
num_elements_a = tf.size(tensor_a)
rank_a = tf.rank(tensor_a)
shape_a = tf.shape(tensor_a)

num_elements_b = tf.size(tensor_b)
rank_b = tf.rank(tensor_b)
shape_b = tf.shape(tensor_b)

In [105]:
print("=== Tensor A ===")
print("Shape:", shape_a.numpy())
print("Rank:", rank_a.numpy())
print("Number of elements:", num_elements_a.numpy())

print("\n=== Tensor B ===")
print("Shape:", shape_b.numpy())
print("Rank:", rank_b.numpy())
print("Number of elements:", num_elements_b.numpy())

=== Tensor A ===
Shape: [  6 300]
Rank: 2
Number of elements: 1800

=== Tensor B ===
Shape: [  6 300]
Rank: 2
Number of elements: 1800
